version: '3.8'

services:
  db:
    image: 'postgres-db:latest'
    build:
      context: ./db-postgres
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"