version: '3.8'

services:
  db:
    image: 'postgres-db:latest'
    build:
      context: ./db-postgres
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"

  ms-customer:
    image: 'ms-customer:latest'
    build:
      context: ./ms-customer
    container_name: ms-customer
    environment:
        - SPRING_PROFILES_ACTIVE=dev
        - DATABASE_USER=postgres
        - DATABASE_PASSWORD=postgres
        - DATABASE_HOST=db
        - DATABASE_PORT=5432
        - DATABASE_NAME=postgres
    ports:
      - "8080:8080"
    links:
      - db